### ISSUE TITLE
"Module not found error" with `npm i -g @colony/pinion`

### ISSUE THREAD

**Issue by aphelionz** [JoinColony/pinion#104]
Node 12.10.0

```
Error: Cannot find module 'multicodec/src/name-table'
Require stack:
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/types/message/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/want-manager/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/components/start.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/components/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/IPFSNode.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/Pinion.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/index.js
- /home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/types/message/index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/types/message/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/want-manager/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs-bitswap/src/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/components/start.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/components/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/node_modules/ipfs/src/core/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/IPFSNode.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/Pinion.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/lib/index.js',
    '/home/mark/.nvm/versions/node/v12.10.0/lib/node_modules/@colony/pinion/bin/index.js'
  ]
}
```

**Comment by aphelionz** [comment]
Update: works checking out from source and running yarn start

**Comment by pepoospina** [comment]
It does not work form me with yarn start either. Same error.

```
Error: Cannot find module 'multicodec/src/name-table'
Require stack:
- /home/pepo/pr/uprtcl/pinion/node_modules/ipfs-bitswap/src/types/message/index.js
...
```
